### ISSUE TITLE
Fast Submodule Update using default options.

### ISSUE THREAD

**Issue by lannick** [anickle060193/tabbed_tortoise_git#67] opened 2017-06-13 15:56 UTC
Suggest adding a "Saved option Fast Submodule Update" to allow one click that will update using the preselected options from the Fast submodule update dialog menu. This will improve the current task of needing to wait for the dialog to open, wait for the modified submodules, and then clicking the update button.

**Comment by anickle060193** [comment] 2017-10-22 06:17
Duplicate of #85

**Closed by anickle060193** 2017-10-22 06:17 UTC
Labels: enhancement
